Diagnostic Report Create for Cardiology and Anatomic pathology
cerner/fhir.cerner.com pull request #1002
Opened 2023-10-13 04:54 UTC by Someshnsn

Description
----

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2023-10-25 09:01 UTC, ashu-bdvt requested changes
Also "Body Fields" are repeated. Keep only 1 such menu

2023-11-02 10:32 UTC, Someshnsn commented on content/millennium/r4/clinical/diagnostics/diagnostic-report.md
> +* Concept Cardiology and Anotomic Pathology are supported for the create operation.
Addressed

2023-11-02 10:32 UTC, Someshnsn commented on content/millennium/r4/clinical/diagnostics/diagnostic-report.md
> +* Diagnostic Report cardiology Write API requires
Addressed

2023-11-03 10:19 UTC, ashu-bdvt requested changes
Please add examples from C1941 which the users can retry if needed. Currently it's from S1941

2023-11-06 04:38 UTC, Someshnsn commented
> Also "Body Fields" are repeated. Keep only 1 such menu

Addressed

2023-11-06 04:39 UTC, Someshnsn commented
> Please add examples from C1941 which the users can retry if needed. Currently it's from S1941

Addressed

2023-11-06 04:44 UTC, ashu-bdvt approved these changes

2023-11-08 11:37 UTC, vinuthnag approved these changes

2023-11-09 06:23 UTC, merged