Updated Immunization DSTU2 Resource
cerner/fhir.cerner.com pull request #1003
Opened 2023-10-13 17:45 UTC by kckeim

Just a handful of changes on this one, including some re-wording of Overview and Implementation Notes sections to be more descriptive / in a similar style to other resources that were recently updated.
Verified good links through document.
Validated that API calls behave as expected with both the expected and unexpected parameters.

Description
----
- Expanded the Overview Section, and more closely matches the verbiage used by HL7.org itself now.
  - Now includes direct links out to the `AllergyIntolerance` and `MedicationAdministration` resources.
- Consolidated Disclaimer, Error, and Outcome sections towards the top.
- Adjusted parameters table's details.
- Expanded on Implementation Notes to match the performance of the API, and explain requirements and expected behavior of each search parameter.

*****************************
PR Checklist
----
- [X] Screenshot(s) of changes attached before changes merged.
- [X] Screenshot(s) of changes attached after changes merged and published.
*****************************
Old Overview:
![image](https://github.com/cerner/fhir.cerner.com/assets/144141792/b7a4054c-8bab-4ea3-8af3-3ca474d08488)

New Overview with links:
![image](https://github.com/cerner/fhir.cerner.com/assets/144141792/739af6c8-cf5f-4d1e-83ce-da5573987045)
*****************************
Old parameters + Implementation Notes:
![image](https://github.com/cerner/fhir.cerner.com/assets/144141792/41bfc2de-fd1d-4f9a-aa17-1fece9c10fb1)

New parameters + Implementation Notes:
![image](https://github.com/cerner/fhir.cerner.com/assets/144141792/d507e3dd-26c6-44a8-a6da-dae4b292d429)

2023-10-17 21:53 UTC, RicardoCrespo-ora approved these changes

2023-10-23 21:11 UTC, summerlcollins approved these changes
approved per [PRODOC-202500](https://jira.cerner.com/browse/PRODOC-202500)

2023-10-26 18:01 UTC, amcginn commented on content/millennium/dstu2/medications/immunization.md
> +An immunization reaction may indicate an allergy or intolerance. If so, a separate [`AllergyIntolerance`] resource instance must be created.
this is a weird business rule/recommendation that I don't think I've seen elsewhere.

@cldeitrich, thoughts on how to approach this one?

2023-10-26 18:04 UTC, amcginn commented on content/millennium/dstu2/medications/immunization.md
> +An immunization reaction may indicate an allergy or intolerance. If so, a separate [`AllergyIntolerance`] resource instance must be created.
looks like this is replicating information from HL7:
https://hl7.org/fhir/DSTU2/immunization.html#bnr

2023-10-26 18:06 UTC, amcginn commented on content/millennium/dstu2/medications/immunization.md
> +  - It can be provided with either a single reference, or a comma-separated list of references. Example `_id=1234` or `_id=1234,5678`
I forget where we had this conversation. do we need to include this on every resource?

2023-10-26 18:08 UTC, amcginn approved these changes

2023-11-15 05:53 UTC, Someshnsn commented
HI @kckeim @summerlcollins 
Should we make this changes for r4
https://fhir.cerner.com/millennium/r4/clinical/medications/immunization/

2023-11-15 05:55 UTC, Someshnsn requested changes
HI @kckeim @summerlcollins
Should we make this changes even for r4?
https://fhir.cerner.com/millennium/r4/clinical/medications/immunization/

2023-11-15 06:02 UTC, Someshnsn commented
HI

> HI @kckeim @summerlcollins Should we make this changes even for r4? https://fhir.cerner.com/millennium/r4/clinical/medications/immunization/

Could see the r4 changes, approving the PR
https://github.com/cerner/fhir.cerner.com/pull/1004

2023-11-15 06:03 UTC, Someshnsn approved these changes

2023-11-16 18:50 UTC, merged