dstu2 Practitioner updates
cerner/fhir.cerner.com pull request #1014
Opened 2023-11-08 16:44 UTC by amcginn

Description
----
* Fields
  * Updated links to 'https'
  * Cleaned up names
  * ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/2cd31791-a498-48f0-afa1-455f7447af72)
  * ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/b8ddabf6-a334-4bfe-8a86-73d7e0e35446)
* Moved disclaimer and error message (see above)
* Updated 'id' to 'ID' throughout
  * ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/f531cfbe-bb2b-4b90-92ac-1a1cb29864b8)
  * ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/a2c229b6-02e3-49af-8f3b-c7b91d5cfe30)
  * ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/bd6f19ec-a61c-47e3-b97c-3124cfcda276)
  * ![image](https://github.com/cerner/fhir.cerner.com/assets/22381097/c3061cac-46f9-4da0-9206-f9fbdee26427)

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [x] Screenshot(s) of changes attached after changes merged and published.

2023-11-09 20:08 UTC, RicardoCrespo-ora approved these changes

2023-11-17 18:49 UTC, kckeim requested changes
This Resource's really simple, so there's not a lot to say anyways.
Looks like you caught all the things I was seeing that would need edits.

2023-11-28 18:52 UTC, kckeim approved these changes

2023-12-15 21:33 UTC, cldeitrich approved these changes
[OHAIUAD-204313](https://jira3.cerner.com/browse/OHAIUAD-204313): Approved for style.

2023-12-16 16:45 UTC, merged

2024-02-02 10:21 UTC, Surya-Rnsit commented
Validated after the code is published:
<img width="1596" alt="Screenshot 2024-02-02 at 3 50 48 PM" src="https://github.com/cerner/fhir.cerner.com/assets/87635660/8de0d7c6-728d-4ea7-9d44-9895b687404a">
<img width="1596" alt="Screenshot 2024-02-02 at 3 51 37 PM" src="https://github.com/cerner/fhir.cerner.com/assets/87635660/27a76a86-48f8-410e-9b1b-bffcd1c6e54c">