R4 Encounter Period StartDateTime Sort Update
cerner/fhir.cerner.com pull request #1033
Opened 2024-01-12 06:55 UTC by ramya1096

Description
----
Update R4 Encounter Sort details

PR Checklist
----
- [X] Screenshot(s) of changes attached before changes merged.
- 
<img width="1261" alt="Screenshot 2024-01-12 at 12 02 26 PM" src="https://github.com/cerner/fhir.cerner.com/assets/55026048/79bebc7a-5879-4bea-9e7f-ba743ac2b044">

- [ ] Screenshot(s) of changes attached after changes merged and published.

2024-01-16 05:26 UTC, shushruth-s approved these changes

2024-01-16 16:37 UTC, mayur-rajendran requested changes

2024-01-16 16:37 UTC, mayur-rajendran commented on content/millennium/r4/base/management/encounter.md
> +* A populated Encounter response bundle will be sorted by start of the [Encounter.period] from oldest to newest order by page. That is, all Encounters on any given page or the next page of results ar
```suggestion
* A populated Encounter response bundle will not have any guaranteed sort order within the page.  However, if the results are split into multiple pages, the pages will be sorted by the start of the [Encounter.period] from newest to oldest.  That is, all encounters on a page will have a newer [Encounter.period] start date than all the encounters on the next page.
```

2024-01-18 14:26 UTC, mayur-rajendran approved these changes

2024-01-19 07:49 UTC, merged

2024-02-02 11:12 UTC, SukeshKonjeti commented
after changes published
<img width="1264" alt="Screenshot 2024-02-02 at 4 41 43 PM" src="https://github.com/cerner/fhir.cerner.com/assets/62686590/7eb058de-d040-40ce-9c01-390a9c403362">