binary_ccd autogen documentation added
cerner/fhir.cerner.com pull request #519
Opened 2020-12-11 13:00 UTC by sonikrish

Description
----

Added documentation for BinaryCCD.

<img width="1649" alt="Screenshot 2020-12-11 at 6 26 02 PM" src="https://user-images.githubusercontent.com/13468284/101906430-f2f73d80-3bde-11eb-8334-ab3f81607379.png">
<img width="1665" alt="Screenshot 2020-12-11 at 6 26 46 PM" src="https://user-images.githubusercontent.com/13468284/101906443-f7bbf180-3bde-11eb-8eee-75ea722262c2.png">
<img width="1668" alt="Screenshot 2020-12-11 at 6 27 46 PM" src="https://user-images.githubusercontent.com/13468284/101906444-f8548800-3bde-11eb-8a93-53e4356e3d80.png">

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2020-12-14 09:19 UTC, aki-mathur requested changes

2020-12-14 09:19 UTC, aki-mathur commented on content/millennium/r4/other/binary.md
> +<%= authorization_types(provider: true, patient: false, system: true) %>
Are we not supporting patient access?

2020-12-14 09:54 UTC, sonikrish commented on content/millennium/r4/other/binary.md
> +<%= authorization_types(provider: true, patient: false, system: true) %>
no not now

2020-12-14 12:50 UTC, aki-mathur approved these changes

2020-12-14 12:53 UTC, vinuthnag approved these changes

2020-12-14 12:57 UTC, merged

2020-12-17 22:44 UTC, VelocityKnight commented
verified live:
![Screen Shot 2020-12-17 at 4 44 39 PM](https://user-images.githubusercontent.com/32784540/102552647-2c202980-4087-11eb-9f08-9b2eba8da8d5.png)