Added Practitioner.qualification field and examples to R4 Practitioner resource
cerner/fhir.cerner.com pull request #649
Opened 2021-05-28 10:58 UTC by ShrutiNHegde

Description
----
Added Practitioner.qualification field and examples to R4 Practitioner resource

Jira:
----
https://jira2.cerner.com/browse/OPENSVC-20284

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2021-05-31 06:57 UTC, NimishaMN approved these changes

2021-05-31 07:00 UTC, gokul-cerner requested changes

2021-05-31 07:00 UTC, gokul-cerner commented on lib/resources/r4/practitioner.yaml
> +  children:
I'm not seeing the "qualification.period" part of the Terminology Bindings. Is this intentional?

2021-05-31 07:18 UTC, gokul-cerner approved these changes

2021-06-01 04:37 UTC, merged

2021-06-03 21:14 UTC, Zonglin123 commented
Validated.
<img width="707" alt="Screen Shot 2021-06-03 at 4 14 27 PM" src="https://user-images.githubusercontent.com/69928745/120712841-c681f700-c486-11eb-9754-38bd0f4518e4.png">