R4 CarePlan _revinclude Provenance
cerner/fhir.cerner.com pull request #770
Opened 2021-11-18 11:18 UTC by khansasultana

Description
----

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2021-11-18 13:00 UTC, aki-mathur requested changes

2021-11-18 13:00 UTC, aki-mathur commented on lib/resources/example_json/r4_examples_care_plan.rb
> +          'url': 'http://localhost:3000/r4/2c400054-42d8-4e74-87b7-80b5bd5fde9f/CarePlan?_id=178866310&_revinclude=Provenance%3Atarget'
Update this url to C1941 domain

2021-11-18 13:00 UTC, aki-mathur commented on lib/resources/example_json/r4_examples_care_plan.rb
> +          'fullUrl': 'http://localhost:3000/r4/2c400054-42d8-4e74-87b7-80b5bd5fde9f/CarePlan/178866310',
Update the URL here aswell

2021-11-18 13:00 UTC, aki-mathur commented on lib/resources/example_json/r4_examples_care_plan.rb
> +          'fullUrl': 'http://localhost:3000/r4/2c400054-42d8-4e74-87b7-80b5bd5fde9f/Provenance/INT.doc-178866310',
Update the url

2021-11-18 13:13 UTC, khansasultana commented on lib/resources/example_json/r4_examples_care_plan.rb
> +          'url': 'http://localhost:3000/r4/2c400054-42d8-4e74-87b7-80b5bd5fde9f/CarePlan?_id=178866310&_revinclude=Provenance%3Atarget'
updated

2021-11-18 13:13 UTC, khansasultana commented on lib/resources/example_json/r4_examples_care_plan.rb
> +          'fullUrl': 'http://localhost:3000/r4/2c400054-42d8-4e74-87b7-80b5bd5fde9f/CarePlan/178866310',
updated

2021-11-18 13:13 UTC, khansasultana commented on lib/resources/example_json/r4_examples_care_plan.rb
> +          'fullUrl': 'http://localhost:3000/r4/2c400054-42d8-4e74-87b7-80b5bd5fde9f/Provenance/INT.doc-178866310',
updated

2021-11-22 05:27 UTC, aki-mathur requested changes

2021-11-22 05:27 UTC, aki-mathur commented on content/millennium/r4/clinical/care-provision/care-plan.md
> + `_revinclude`| No        | [`token`]  | Provenance resource entries to be returned as part of the bundle. Example:_revinclude=Provenance:target
nit: This should be aligned correctly

2021-11-22 05:39 UTC, vinuthnag requested changes

2021-11-22 05:39 UTC, vinuthnag commented on content/millennium/r4/clinical/care-provision/care-plan.md
> + `_revinclude`| No        | [`token`]  | Provenance resource entries to be returned as part of the bundle. Example:_revinclude=Provenance:target
+1

2021-11-22 05:45 UTC, khansasultana commented on content/millennium/r4/clinical/care-provision/care-plan.md
> + `_revinclude`| No        | [`token`]  | Provenance resource entries to be returned as part of the bundle. Example:_revinclude=Provenance:target
addressed

2021-11-22 05:46 UTC, aki-mathur approved these changes

2021-11-22 06:33 UTC, vinuthnag approved these changes

2021-12-02 10:12 UTC, merged

2021-12-02 12:55 UTC, aki-mathur commented
<img width="1625" alt="Screenshot 2021-12-02 at 6 25 20 PM" src="https://user-images.githubusercontent.com/18599901/144426075-b3605d75-7f5e-49ec-8d5e-6c3b2b348e11.png">