documents reference r4 enhancement
cerner/fhir.cerner.com pull request #858
Opened 2022-07-04 12:09 UTC by akashdeep677

Description
----

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2022-07-04 12:11 UTC, akashdeep677 commented
<img width="1792" alt="Screenshot 2022-07-04 at 5 29 15 PM" src="https://user-images.githubusercontent.com/32587557/177152033-5e380cae-72fc-4320-bb7c-48120f673f15.png">
<img width="1792" alt="Screenshot 2022-07-04 at 5 28 56 PM" src="https://user-images.githubusercontent.com/32587557/177152065-a0053265-d2db-47a9-bedc-75ae64254ccf.png">

2022-07-04 12:48 UTC, Sanvenky requested changes

2022-07-04 12:48 UTC, Sanvenky commented on content/millennium/r4/foundation/documents/document-reference.md
> +Read operation is supported for clinical-note, cardiology, radiology, microbiology and pathology charted documents and clinical-note staged documents.
This should go under read implementation notes

2022-07-04 12:48 UTC, Sanvenky commented on content/millennium/r4/foundation/documents/document-reference.md
> +  * `Period` and `date` search parameter cannot be provided together.
remove this line. Its covered down

2022-07-19 05:50 UTC, akashdeep677 commented
Please consider below PR -
https://github.com/cerner/fhir.cerner.com/pull/864

2022-07-19 05:50 UTC, closed without merging