Soarian Capability statement Overview page issue fix
cerner/fhir.cerner.com pull request #867
Opened 2022-07-25 09:08 UTC by VamsiMure

Description
----

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2022-07-25 10:18 UTC, PBKarthik approved these changes

2022-07-26 13:18 UTC, stanlysampath approved these changes

2022-07-27 13:47 UTC, PBKarthik approved these changes

2022-07-28 10:02 UTC, PBKarthik approved these changes

2022-08-01 11:11 UTC, ashu-bdvt requested changes
Also please add 2-3 more screenshots highlighting the changes to the menus and other documentation changes

2022-08-01 11:11 UTC, ashu-bdvt commented on content/soarian/r4/clinical/diagnostics/diagnostic-report.md
> +    * Organization
Indentation mismatch

2022-08-01 15:11 UTC, VamsiMure commented on content/soarian/r4.md
> +Scopes supported: launch, launch/patient, openid, fhirUser, offline_access, online_access, profile, patient/AllergyIntolerance.read, patient/Binary.read, patient/CarePlan.read, patient/CareTeam.read,
Could you be more specific on whats the change here. Is it the space ?

2022-08-02 08:38 UTC, VamsiMure commented on content/soarian/r4.md
> +Scopes supported: launch, launch/patient, openid, fhirUser, offline_access, online_access, profile, patient/AllergyIntolerance.read, patient/Binary.read, patient/CarePlan.read, patient/CareTeam.read,
I have updated the content as suggested

2022-08-02 08:39 UTC, VamsiMure commented on content/soarian/r4/clinical/diagnostics/diagnostic-report.md
> +    * Organization
updated

2022-08-02 10:38 UTC, ashu-bdvt commented on content/soarian/r4.md
> +Scopes supported: launch, launch/patient, openid, fhirUser, offline_access, online_access, profile, patient/AllergyIntolerance.read, patient/Binary.read, patient/CarePlan.read, patient/CareTeam.read,
> Could you be more specific on whats the change here. Is it the space ?

yes

2022-08-02 10:39 UTC, ashu-bdvt approved these changes

2022-08-03 10:59 UTC, merged

2022-08-04 13:35 UTC, aki-mathur commented
<img width="1404" alt="Screenshot 2022-08-04 at 7 03 28 PM" src="https://user-images.githubusercontent.com/18599901/182859984-703f5b7e-6708-495a-baf1-88e54556b5af.png">

<img width="1404" alt="Screenshot 2022-08-04 at 7 03 54 PM" src="https://user-images.githubusercontent.com/18599901/182860082-12ff0069-1410-4e86-8ce3-6e6ff5edb44e.png">