R4 - Update Condition Overview
cerner/fhir.cerner.com pull request #886
Opened 2022-09-01 14:50 UTC by learclite

Description
----
Condition resource updates

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2022-09-01 14:52 UTC, learclite commented
Before:
<img width="1079" alt="Screenshot 2022-09-01 at 17 47 40" src="https://user-images.githubusercontent.com/28542791/187944609-eb3d0323-e22b-4c48-9d65-7c8d90369fa3.png">

After commit 5f932fd :
<img width="1087" alt="Screenshot 2022-09-01 at 17 44 47" src="https://user-images.githubusercontent.com/28542791/187944868-e906b29a-85d9-4294-bd24-c001baba0013.png">

2022-09-02 08:03 UTC, lstefan4 approved these changes

2022-09-02 08:45 UTC, lstefan4 approved these changes

2022-09-06 17:01 UTC, cerbs requested changes

2022-09-07 10:46 UTC, learclite commented on content/millennium/r4/clinical/summary/condition.md
> +  * [Reference](https://hl7.org/fhir/r4/references.html#Reference){:target="_blank"} ([Practitioner](https://hl7.org/fhir/r4/practitioner.html){:target="_blank"}) \| [string](https://hl7.org/fhir/R4/
Changed in commit d2a4efc : 
<img width="786" alt="Screenshot 2022-09-07 at 13 44 22" src="https://user-images.githubusercontent.com/28542791/188859835-ce5998db-b9d9-49d7-be19-2e2edf1dfe6e.png">

2022-09-07 19:14 UTC, cerbs approved these changes

2022-09-07 19:26 UTC, davischristi approved these changes

2022-09-08 08:07 UTC, merged