R4 - Add patient resource updates
cerner/fhir.cerner.com pull request #888
Opened 2022-09-02 12:21 UTC by napster235

Description
----
Add patient resource updates

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2022-09-02 12:21 UTC, napster235 commented
Before
<img width="788" alt="Screenshot 2022-09-02 at 15 01 40" src="https://user-images.githubusercontent.com/20145349/188141677-e7b56234-13fa-4d30-b28a-10be64e8fc13.png">
After commit a2e1364
<img width="784" alt="Screenshot 2022-09-02 at 15 20 51" src="https://user-images.githubusercontent.com/20145349/188141730-6f1e7526-6a26-4d7a-823b-96d1ab2d987a.png">

2022-09-02 12:23 UTC, lstefan4 approved these changes

2022-09-06 17:43 UTC, cerbs requested changes

2022-09-06 17:43 UTC, cerbs commented on content/millennium/r4/base/individuals/patient.md
> +  * [Usual](https://hl7.org/fhir/R4/codesystem-identifier-use.html#identifier-use-usual){:target="_blank"}
Usual isn't an identifier field. Not sure the best way to represent this. Perhaps an implementation note in the read/search sections to indicate that the identifier.use will be 'usual'?

2022-09-07 08:02 UTC, napster235 commented
After commit 6903480
<img width="725" alt="Screenshot 2022-09-07 at 10 59 38" src="https://user-images.githubusercontent.com/20145349/188823946-9ce8b831-8b01-4051-b7e0-77c18b7f5c20.png">
<img width="725" alt="Screenshot 2022-09-07 at 10 59 21" src="https://user-images.githubusercontent.com/20145349/188823961-63d96a0e-4156-42d2-bb35-03574faa4318.png">

2022-09-07 19:10 UTC, davischristi approved these changes

2022-09-08 17:22 UTC, cerbs commented on content/millennium/r4/base/individuals/patient.md
> +* Usual will be represented by [Identifier.use](https://hl7.org/fhir/R4/datatypes-definitions.html#Identifier.use){:target="_blank"}
Looks like I got interrupted yesterday and didn't get this comment posted yesterday. The wording here and line 149 is a bit backward. "Usual" represents the identifier's use, not the other way around.

Perhaps:
```suggestion
* [Patient.identifier.use](https://hl7.org/fhir/R4/datatypes-definitions.html#Identifier.use){:target="_blank"} will have a value of `usual`
```

2022-09-08 17:22 UTC, cerbs commented on content/millennium/r4/base/individuals/patient.md
> +* Usual will be represented by [Identifier.use](https://hl7.org/fhir/R4/datatypes-definitions.html#Identifier.use){:target="_blank"}
```suggestion
* [Patient.identifier.use](https://hl7.org/fhir/R4/datatypes-definitions.html#Identifier.use){:target="_blank"} will have a value of `usual`
```

2022-09-09 08:50 UTC, napster235 commented
After commit [3a831af](https://github.com/cerner/fhir.cerner.com/pull/888/commits/3a831aff80c9b74081e0316c31761631a12b3516)
<img width="589" alt="Screenshot 2022-09-09 at 11 49 03" src="https://user-images.githubusercontent.com/20145349/189311211-4e21ac35-219b-4e74-8e31-3fb81e2929c7.png">
<img width="589" alt="Screenshot 2022-09-09 at 11 49 52" src="https://user-images.githubusercontent.com/20145349/189311223-86c4fe2f-fcb4-4631-a7d1-6b60461f09b1.png">

2022-09-09 11:54 UTC, cerbs approved these changes

2022-09-09 12:37 UTC, merged