R4 - Update MedicationRequest Overview
cerner/fhir.cerner.com pull request #896
Opened 2022-09-14 12:12 UTC by PorosnicuCornel

Description
----
https://jira2.cerner.com/browse/OPENSVC-24044
Updates for the FHIR resource: MedicationRequest.

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2022-09-14 12:29 UTC, MariaPislaru1 approved these changes

2022-09-14 13:18 UTC, lstefan4 approved these changes

2022-09-19 18:31 UTC, davischristi commented
Can you add the screenshot of the listed profile?

2022-09-20 07:11 UTC, PorosnicuCornel commented
> 

![image](https://user-images.githubusercontent.com/19925458/191191095-1d115e31-9cf8-4f6a-acd4-8066dee453bf.png)

2022-09-26 20:03 UTC, davischristi requested changes
Also remove the link to the jira from the description.

2022-09-27 07:42 UTC, PorosnicuCornel commented
> Also remove the link to the jira from the description.

done

2022-09-27 07:56 UTC, PorosnicuCornel commented on content/millennium/r4/clinical/medications/medication-request.md
>  * [Dispensing Details](https://hl7.org/fhir/r4/medicationrequest-definitions.html#MedicationRequest.dispenseRequest){:target="_blank"}
<img width="246" alt="image" src="https://user-images.githubusercontent.com/19925458/192467626-1de74818-1e3b-42d1-a136-b6eb623d0d54.png">
done

2022-09-27 07:57 UTC, PorosnicuCornel commented on content/millennium/r4/clinical/medications/medication-request.md
> +  * [CodeableConcept](https://hl7.org/fhir/r4/datatypes.html#CodeableConcept){:target="_blank"}
<img width="354" alt="image" src="https://user-images.githubusercontent.com/19925458/192467799-9e363c83-0824-4631-aebd-0c025b0fa1e0.png">

done

2022-09-27 14:17 UTC, davischristi approved these changes

2022-09-27 14:20 UTC, merged

2022-09-28 20:13 UTC, ebbp123 commented
Looks like some spaces were added in line 8 which broke the table of contents for the resource: 
<img width="564" alt="Screen Shot 2022-09-28 at 3 11 56 PM" src="https://user-images.githubusercontent.com/18171913/192879433-4393dfc2-ed12-4d6d-b7bb-a2ab4b6ecabc.png">

2022-09-28 20:33 UTC, ebbp123 commented
PR to Fix the TOC: https://github.com/cerner/fhir.cerner.com/pull/905