Review and corrections for ChargeItem
cerner/fhir.cerner.com pull request #976
Opened 2023-09-05 21:22 UTC by RicardoCrespo-ora

Description
----
In preparation for migrating to Oracle docs, we are reviewing and correcting any inconsistencies, typos, broken links, etc. This PR aims to correct any of the above that needs to be addressed within ChargeItem and any other information directly referenced by it.

Within Chargeitem.extension[x].extension[x].valueCodeableConcept for procedure-codes anchor link is broken, it should be https://fhir.cerner.com/millennium/r4/financial/general/charge-item/#extension

**Before**:
<img width="935" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/d6cd35f5-2f9e-47ed-8951-82666493d61e">
**After**: 
<img width="911" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/76ca75d8-f6fe-409f-a08d-5612f6900ad1">

When clicking Bill Code types for Chargeitem.extension[x].extension[x].valueCodeableConcept for procedure-codes, its corresponding bill type code PROCCODE is missing from the list of possible bill type codes. 

**Before**: 
<img width="809" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/96c74d5a-b9b0-4165-9887-97a7fb3dde36">
**After**:
<img width="743" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/836796db-ad61-4dd2-80e1-e2c29653c8a0">

Chargeitem.extension[x].valueCodeableConcept for revenue-code should have the same depth as modifier code and procedure code extensions: extension[x].extension[x].valueCodeableConcept, as that is how it appears on live json responses.

**Before**:
<img width="794" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/eba21559-0a19-4445-acd6-2ac0f957c3fd">
**After**: 
<img width="694" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/3e27811b-9c79-4200-8c7c-0d39082f1b92">

Chargeitem.extension[x].extension[x].valueCodeableConcept for national-drug-product has a Broken url in Details for National Drug Product: https://hl7.org/fhir/sid/ndc will redirect to https://hl7.org/fhir/http://terminology.hl7.org/5.1.0/CodeSystem-v3-ndc.html which returns a Server Error, should be https://terminology.hl7.org/5.1.0/CodeSystem-v3-ndc.html

**Before**: 
<img width="791" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/64460625-f87d-4f75-8e63-0f05c685f0a1">
![image](https://github.com/cerner/fhir.cerner.com/assets/143555600/a2c665be-66ba-4133-9f4a-d418e9939174)

**After**:
<img width="692" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/8454b6b9-669e-45fe-8cb5-ad29465204bb">
<img width="1114" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/e095015b-654b-4e29-93d2-a04b079086f2">

For Operations charge-item-credit, charge-item-modify, charge-item-create, their top of section anchor links don’t work properly, this is because in the table they are defined with the prefix operation-charge-item but the metadata endpoint (https://fhir-ehr-code.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/metadata) has them defined as #credit, #modify and #create respectively, and the anchor url is automatically defined from that. This change aims to make them match with the response from metadata so that the proper anchor url is generated.

**Before**
<img width="409" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/72127ac8-4ec8-42bb-8b30-6423dca36d7b">

**After**
<img width="296" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/624a5834-0a0f-4e73-84f0-17548a1c4590">

Create URL includes an :id, but this endpoint shouldn't have an id parameter, the example correctly omits it 

**Before**
<img width="296" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/cae37327-43ec-4557-9ad2-09887bbcb646">

**After**
<img width="712" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/5501995f-787e-40ee-80fc-34e196959c7a">

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [x] Screenshot(s) of changes attached after changes merged and published.

2023-09-06 14:40 UTC, amcginn commented
ChargeItem Create "before" image is incorrect

2023-09-06 14:43 UTC, amcginn requested changes

2023-09-06 14:43 UTC, amcginn commented on content/millennium/r4/proprietary-codes-and-systems.md
> +This system is the bill code type for a charge item. `Bill code type` can be either `CDM_SCHED`, `CPT`, `HCPCS`, `ICD`, `PROCCODE` , `MODIFIER`, or `REVENUE`.
nit: remove the space before the comma.

2023-09-06 14:43 UTC, amcginn commented on lib/resources/r4/charge_item.yaml
> +          system: https://terminology.hl7.org/5.1.0/CodeSystem-v3-ndc.html
it's ok to change the link, but the "system" needs to stay the same, as that is the official system of the NDC values

2023-09-06 14:57 UTC, RicardoCrespo-ora commented
> ChargeItem Create "before" image is incorrect

Updated with correct image. Thanks

2023-09-06 15:35 UTC, amcginn approved these changes

2023-09-07 15:30 UTC, kckeim approved these changes
This all looked appropriate to me - you did a great job with getting supporting screenshots and such

2023-09-07 16:03 UTC, krycunn approved these changes
Looks great! Love the before and after screenshots 🔥

2023-09-13 06:52 UTC, merged

2023-09-29 09:22 UTC, JagatNayak commented
After Publish 
<img width="1792" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/b3d76d47-ec8f-49d9-ab32-c3cb26f51a9e">