Custom Encounter Search
cerner/fhir.cerner.com pull request #978
Opened 2023-09-14 07:47 UTC by Nandita92

Description
----

PR Checklist
----

- [x] Screenshot(s) of changes attached before changes merged.

<img width="1
<img width="1393" alt="Screenshot 2023-09-14 at 1 15 16 PM" src="https://github.com/cerner/fhir.cerner.com/assets/33324957/fea9215c-f1c7-4573-b7f6-6f9299a84e0b">
393" alt="Screenshot 202
<img width="1393" alt="Screenshot 2023-09-14 at 1 15 51 PM" src="https://github.com/cerner/fhir.cerner.com/assets/33324957/89a136cf-cffb-4893-9bb8-f827d84ccbc5">
3-09-14 at 1 15
<img width="1
<img width="1393" alt="Screenshot 2023-09-14 at 1 15 00 PM" src="https://github.com/cerner/fhir.cerner.com/assets/33324957/80f34076-672e-4ce9-aebd-fd1ce9688cc3">

- [ ] Screenshot(s) of changes attached after changes merged and published.

2023-09-14 10:27 UTC, SantanuBanerjee commented on content/millennium/r4/financial/general/account.md
> +    GET https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Account??encounter=98028029&type=guarantor-balance
There are 2 question marks after /Account

2023-09-15 04:53 UTC, SantanuBanerjee approved these changes

2023-09-25 04:45 UTC, BhavyaAcharya approved these changes

2023-09-25 11:38 UTC, ashu-bdvt requested changes
Also update the PR title and do not include Jira IDs per the best practices defined. Since this is public repo we should not include the Jira #

2023-09-25 11:38 UTC, ashu-bdvt commented on content/millennium/r4/financial/general/account.md
> +`-encounter`  | See notes | [`reference`] | The id to identify the encounter. Example: `98028029`
Needs 1 more space to align with the above lines

2023-09-25 11:38 UTC, ashu-bdvt commented on content/millennium/r4/financial/general/account.md
> +    GET https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Account??encounter=98028029&type=guarantor-balance
+1

2023-09-25 14:08 UTC, Nandita92 commented on content/millennium/r4/financial/general/account.md
> +    GET https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/Account??encounter=98028029&type=guarantor-balance
Updated here: https://github.com/cerner/fhir.cerner.com/commit/ff9aada138eefe2277802799a9124a96e5611328#diff-c95b06a9fe9f63e4cd5352c5f6cb27d71a28bcef3c8d6226c833a912332f4556R127

2023-09-25 14:12 UTC, closed without merging