Consent updated examples
cerner/fhir.cerner.com pull request #986
Opened 2023-09-21 15:16 UTC by RicardoCrespo-ora

Description
----
Updated examples for `Search by Id` and `Search by Actor` with updated data which was previously showing outdated data

**Before**
![image](https://github.com/cerner/fhir.cerner.com/assets/143555600/2cfc980a-9475-4223-9ffe-f4a994eee9f1)

**After**
<img width="809" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/504e31db-a654-4454-9c4c-283ba3def0d5">

---

**Before**
<img width="865" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/e3769f65-3e70-4d50-aeba-2c08487974f6">

**After**
<img width="834" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/143555600/6b3cdb13-8e61-4f67-8abc-e2bb52949c60">

PR Checklist
----
- [x] Screenshot(s) of changes attached before changes merged.
- [x] Screenshot(s) of changes attached after changes merged and published.

2023-09-21 18:05 UTC, kckeim requested changes
Sorry you had trouble with JSON formatting behaving on this one, @RicardoCrespo-ora.

The changes you made look okay from my perspective.
I would add some backticks around the details in the "Description" column around the parameters in the consent.md file - we have them for a few of the examples, but not all of them.
e.g.
actor=RelatedPerson/1234
->
`actor=RelatedPerson/1234`
*************************************
![image](https://github.com/cerner/fhir.cerner.com/assets/144141792/b9fe4c48-f0dd-4d9b-9bef-c4b22e4d6c51)

*************************************
Beyond that, I like this

2023-09-21 18:21 UTC, kckeim commented
Thanks for fixing stuff, @RicardoCrespo-ora.

Approved from my side now

2023-09-21 18:21 UTC, kckeim approved these changes

2023-09-21 20:01 UTC, amcginn approved these changes

2023-09-22 08:50 UTC, lstefan4 approved these changes

2023-09-22 14:05 UTC, merged