R4_UK_BRAM_Update_Slot_include
cerner/fhir.cerner.com pull request #994
Opened 2023-10-05 07:45 UTC by JagatNayak

Description
----
R4_UK_BRAM_Update_Slot_include

PR Checklist
----
- [ ] Screenshot(s) of changes attached before changes merged.
- [ ] Screenshot(s) of changes attached after changes merged and published.

2023-10-05 07:52 UTC, JagatNayak commented
<img width="1143" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/d4c02c9b-67b3-43a8-93d3-fe95526dc934">

2023-10-05 07:52 UTC, JagatNayak commented
Implementation Note: 
<img width="1143" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/e2fff0eb-5bf1-4e1b-a6ec-4bcf8f7b58a0">

2023-10-05 07:54 UTC, JagatNayak commented
Example with Include  when **_include=Slot:schedule** :
<img width="1143" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/3be71562-79da-4bd1-95ad-4d66351ddf37">

2023-10-05 07:55 UTC, JagatNayak commented
Example with Include when _include=Schedule :actor:Practitioner  :
<img width="1143" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/14df3557-bee7-4bc4-9d38-54c38f1fdc40">

2023-10-05 07:57 UTC, JagatNayak commented
Patient Authorization Request when _include=Slot:schedule : 

<img width="1143" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/ea642090-e105-4b24-ab11-056f1d147c6e">

2023-10-05 07:58 UTC, JagatNayak commented
Patient Authorization Request when _include=Schedule:acto:Practitioner :
<img width="1143" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/ea25a8a6-4cf7-4054-a47d-083903b42d10">

2023-10-05 12:25 UTC, ashu-bdvt requested changes

2023-10-05 12:25 UTC, ashu-bdvt commented on content/millennium/r4/base/workflow/slot.md
> +*  When `_include=Schedule:actor:Practitioner` is provided in a request to the closed endpoint, the OAuth2 token must include  one of `user/Practitioner.read`, `patient/Practitioner.read` or `system/
```suggestion
*  When `_include=Schedule:actor:Practitioner` is provided in a request to the closed endpoint, the OAuth2 token must include  one of `user/Practitioner.read`, `patient/Practitioner.read` or `system/Practitioner.read` scopes and one of `user/Schedule.read`, `patient/Schedule.read` or `system/Schedule.read` scopes in addition to the Slot scope.
```

2023-10-05 12:46 UTC, JagatNayak commented
Addressed comment :
<img width="1143" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/dd2b4d98-0ecf-4018-9244-bb539ab88811">

2023-10-09 04:11 UTC, NimishaMN approved these changes

2023-10-09 06:09 UTC, JagatNayak commented
Before Changes :
<img width="783" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/0e3475ae-b805-4f1f-85ec-256f18e2f342">

2023-10-09 06:10 UTC, JagatNayak commented
Before Changes Implementation :
<img width="1159" alt="image" src="https://github.com/cerner/fhir.cerner.com/assets/65965700/59c1dcaf-0ff1-48fe-af07-2bf3dde3b5f9">

2023-10-09 12:33 UTC, ashu-bdvt approved these changes

2023-10-09 12:34 UTC, merged

2023-11-10 09:57 UTC, Surya-Rnsit commented
After Release:
<img width="1792" alt="Screenshot 2023-11-10 at 3 25 59 PM" src="https://github.com/cerner/fhir.cerner.com/assets/87635660/1d102bc2-7fcc-4324-94fb-71e25c7e91b0">
<img width="1792" alt="Screenshot 2023-11-10 at 3 24 52 PM" src="https://github.com/cerner/fhir.cerner.com/assets/87635660/3899e404-d05c-4df2-8940-00a22ffeaefb">